# Generated by Django 4.2 on 2024-05-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('spell_checked_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Copy.pdfdocument')),
            ],
        ),
    ]
